server:
  tomcat:
    basedir: ./
  port: 7443

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
  datasource:
    url: jdbc:postgresql://mosesjebish.postgres.database.azure.com:5432/postgres?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory&sslmode=require
    username: mosesjebish@mosesjebish
    password: database@123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        show_sql: true
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.xml