spring:
  datasource:
    url: jdbc:postgresql://mosesjebish.postgres.database.azure.com:5432/postgres?ssl=true
    username: mosesjebish@mosesjebish
    password: database@123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        show_sql: true
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog-master.xml